/* Motheo Digital Cafe — Fix It Yourself: troubleshooting flows.
 *
 * All steps below are written for this shop. Nothing is copied from anywhere.
 * The `ifixit` link on each flow points OUT to ifixit.com so people can read a
 * full teardown if they want one — we link, we do not republish.
 *
 * Adding a flow: copy a block, keep the shape. `device` must match a DEVICES id.
 * The Search URLs always resolve; swap in an exact article URL when you find one,
 * e.g. https://www.ifixit.com/Troubleshooting/Samsung_Android_Phone/Not+Charging/562997
 */

const DEVICES = [
  { id: 'phone',   name: 'Phone',           note: 'Android or iPhone' },
  { id: 'laptop',  name: 'Laptop',          note: 'Any make' },
  { id: 'desktop', name: 'Desktop PC',      note: 'Tower and monitor' },
  { id: 'printer', name: 'Printer',         note: 'Home or office' },
  { id: 'network', name: 'WiFi / internet', note: 'Router and data' },
];

const FLOWS = [
  /* ------------------------------------------------------------- PHONE */
  {
    id: 'phone-charge', device: 'phone', title: 'Not charging',
    blurb: 'Plugged in but the battery is not moving.', mins: 10,
    ifixit: {
      label: 'Samsung Android — Not Charging',
      url: 'https://www.ifixit.com/Troubleshooting/Samsung_Android_Phone/Not+Charging/562997',
    },
    steps: [
      { t: 'Swap the cable, then swap the charger',
        d: 'Borrow a cable and a plug you know work on another phone. Test them one at a time so you know which one was the problem.',
        tip: 'This is the answer more often than anything else on this list. Cables fail at the bend near the plug, and it does not show from the outside.' },
      { t: 'Look inside the charging port with a torch',
        d: 'Pocket lint compacts into a hard block at the bottom of the port, so the cable seats but never touches the contacts. Switch the phone off, then lift the lint out with a wooden toothpick.',
        tip: 'Wood or plastic only. Never a pin, a needle, a paperclip or a SIM tool — the contacts sit right there and bending one turns a free fix into a port replacement.' },
      { t: 'Charge from a wall socket',
        d: 'Not a laptop USB port, not a multiplug that already has a kettle or a heater on it. Give it a socket of its own.',
        tip: 'A laptop USB port often supplies too little current to outpace a phone that is awake.' },
      { t: 'Force a restart while it is plugged in',
        d: 'Hold power and volume-down together for about 20 seconds until it reboots. On an iPhone: volume-up, volume-down, then hold the side button.',
        tip: 'A frozen phone can be drawing power and refusing to display anything about it.' },
      { t: 'Leave it off and charging for two hours',
        d: 'Switch the phone off completely and leave it on the charger. A battery that has gone very flat can take 45 minutes before the screen will show anything at all.',
        tip: 'Come back to it. Checking every five minutes wakes the screen and slows the charge down.' },
    ],
    giveUp: 'That leaves the battery or the charging port, and both need the phone opened. Bring it in — diagnosis is R50 and comes off the bill if you go ahead.',
  },
  {
    id: 'phone-dead', device: 'phone', title: 'Will not switch on',
    blurb: 'No screen, no vibration, nothing.', mins: 8,
    ifixit: { label: 'Phone will not turn on', url: 'https://www.ifixit.com/Search?query=phone+won%27t+turn+on' },
    steps: [
      { t: 'Force a restart',
        d: 'Power and volume-down held together for 20 seconds. Do this even if you are sure the phone is dead — a frozen phone looks exactly like a flat one.' },
      { t: 'Charge for 30 minutes first, then try again',
        d: 'Use a wall socket and a cable you have tested on another phone. Look for any charging symbol, even a faint one.',
        tip: 'No charging symbol after 30 minutes on a known-good charger is a real signal. Note that down.' },
      { t: 'Check the screen is not just dark',
        d: 'Take it into a dark room and shine a torch at the screen at a low angle. If you can make out faint icons, the phone is running and the backlight has failed.',
        tip: 'That is a much cheaper repair than a dead board, and knowing it before you arrive saves us both time.' },
      { t: 'Feel for warmth after 15 minutes on charge',
        d: 'Slightly warm near the port or the middle of the back means it is drawing power. Stone cold usually means it is not.' },
    ],
    giveUp: 'A phone that stays cold and dark on a known-good charger needs opening. Bring it in with the charger you have been using.',
  },
  {
    id: 'phone-full', device: 'phone', title: 'Storage full or very slow',
    blurb: 'Cannot take photos, apps crashing, everything lagging.', mins: 15,
    ifixit: { label: 'Phone performance', url: 'https://www.ifixit.com/Search?query=android+slow+performance' },
    steps: [
      { t: 'Find out what is actually using the space',
        d: 'Settings, then Storage. Read the breakdown before deleting anything. People delete photos they wanted and it turns out the space went somewhere else entirely.' },
      { t: 'Clear WhatsApp media',
        d: 'WhatsApp, Settings, Storage and data, Manage storage. Sort by size. Forwarded videos in group chats are usually the biggest single thing on the phone.',
        tip: 'Review before you delete. Anything you delete here is gone from the phone.' },
      { t: 'Restart the phone',
        d: 'A full power-off and on, not just locking the screen. Phones that have not been restarted in weeks slow down noticeably.' },
      { t: 'Uninstall what you have not opened in six months',
        d: 'Long-press the app icon, uninstall. Preinstalled apps you cannot remove can usually be disabled instead.' },
    ],
    giveUp: 'Still full? Bring the phone and a USB stick — we copy your photos off and clear the phone properly. Scan-and-transfer is R5 a batch.',
  },

  /* ------------------------------------------------------------ LAPTOP */
  {
    id: 'laptop-dead', device: 'laptop', title: 'Will not switch on',
    blurb: 'No lights, no fan, nothing when you press power.', mins: 10,
    ifixit: { label: 'Laptop will not turn on', url: 'https://www.ifixit.com/Search?query=laptop+won%27t+turn+on' },
    steps: [
      { t: 'Check the charger has a light, and the socket has power',
        d: 'Plug something else into the same socket to prove the socket works. Then look for an LED on the charger brick or on the laptop where the charger goes in.',
        tip: 'Test the socket before you blame the laptop. This catches a surprising number of "dead" machines.' },
      { t: 'Do a hard reset',
        d: 'Unplug the charger. If the battery comes out, take it out. Hold the power button down for 30 full seconds. Put the battery back, plug the charger in, then press power.',
        tip: 'This drains residual charge from the board and clears a stuck power state. It works often enough to always be worth doing.' },
      { t: 'Watch and listen carefully for five seconds after pressing power',
        d: 'Any light? Any fan? Any beep? Nothing at all points at power delivery. Lights and fan but a black screen is a different problem — go to the black screen flow instead.' },
      { t: 'Try without the battery, charger only',
        d: 'If the battery is removable, run on mains alone. A failed battery can stop the whole machine from starting.' },
    ],
    giveUp: 'No lights on mains after a hard reset means the charger, the power jack or the board. Bring the laptop and its charger — we test both. Diagnosis R50, waived if you go ahead.',
  },
  {
    id: 'laptop-black', device: 'laptop', title: 'Powers on, screen stays black',
    blurb: 'Fan spins and lights come on, but nothing on the display.', mins: 12,
    ifixit: { label: 'Laptop screen problems', url: 'https://www.ifixit.com/Search?query=laptop+black+screen' },
    steps: [
      { t: 'Turn the brightness right up',
        d: 'Find the brightness keys on the F-row, usually a sun symbol. Hold Fn and press the brighter one about ten times. Brightness gets knocked to zero more often than you would think.' },
      { t: 'Torch test for the backlight',
        d: 'In a dark room, shine a torch on the screen at an angle. Faint desktop or a login box visible means the laptop is running fine and only the backlight has failed.',
        tip: 'Write down what you saw. It changes the repair and the price.' },
      { t: 'Plug it into a TV with an HDMI cable',
        d: 'Set the TV to that HDMI input. Press the display key (usually Fn and F4, F5 or F8) a few times.',
        tip: 'Picture on the TV proves the machine and the graphics work. The fault is the screen, the hinge cable, or the lid sensor.' },
      { t: 'Open and close the lid slowly',
        d: 'The lid sensor tells the laptop to sleep. A stuck one keeps the screen off while everything else runs.' },
    ],
    giveUp: 'Screen replacement starts at R950 including a common panel. Bring it in and we will confirm the exact panel before ordering anything.',
  },
  {
    id: 'laptop-slow', device: 'laptop', title: 'Painfully slow',
    blurb: 'Takes minutes to start, freezes, spinning circle.', mins: 20,
    ifixit: { label: 'Slow computer', url: 'https://www.ifixit.com/Search?query=slow+computer' },
    steps: [
      { t: 'Shut down properly, then start again',
        d: 'Start menu, Power, Shut down. Not Sleep, not just closing the lid. Many laptops have not truly restarted in months.' },
      { t: 'Check free space on the C: drive',
        d: 'Open This PC and look at the bar under C:. Under about 10% free and Windows slows to a crawl because it has no room to work.',
        tip: 'Downloads and the Recycle Bin are the quickest wins. Empty the bin properly afterwards.' },
      { t: 'Cut the startup list',
        d: 'Ctrl, Shift and Escape together opens Task Manager. Startup tab. Disable anything you did not deliberately install. Leave anything with your antivirus name on it alone.' },
      { t: 'Check what type of drive it has',
        d: 'In Task Manager, Performance tab, click Disk. If it says HDD and the machine runs Windows 10 or 11, that is your answer — the drive cannot keep up with the operating system.',
        tip: 'An SSD upgrade is the single biggest change you can make to an old laptop. R250 labour plus the drive, and it usually feels like a new machine.' },
      { t: 'Look for something eating the CPU',
        d: 'Task Manager, Processes tab, click the CPU column to sort. Anything sitting at 90% while you are doing nothing is worth a photo.' },
    ],
    giveUp: 'Send us a photo of the Task Manager Performance tab on WhatsApp and we will tell you whether it is worth upgrading or replacing before you spend anything.',
  },
  {
    id: 'laptop-hot', device: 'laptop', title: 'Overheating or loud fan',
    blurb: 'Hot underneath, fan roaring, switching itself off.', mins: 10,
    ifixit: { label: 'Laptop overheating', url: 'https://www.ifixit.com/Search?query=laptop+overheating' },
    steps: [
      { t: 'Put it on a hard flat surface',
        d: 'A bed, a couch or your lap blocks the intake vents underneath. A table, a tray or a book is enough.' },
      { t: 'Look at the vents',
        d: 'Shine a torch into the side and bottom grilles. A grey felt of dust across the fins means no air is moving through, no matter how fast the fan spins.' },
      { t: 'Find out what is working it that hard',
        d: 'Task Manager, Processes, sort by CPU. A browser with thirty tabs, or something you did not install, is often the whole story.' },
      { t: 'Shut it down and let it cool if it is switching itself off',
        d: 'Thermal shutdown is a protection. Repeatedly restarting a machine that keeps cutting out shortens its life.',
        tip: 'Stop here rather than pushing through. This one is worth bringing in.' },
    ],
    giveUp: 'An internal clean and fresh thermal paste is part of our R250 service. Bring it in before it cooks the board — that repair costs far more.',
  },
  {
    id: 'laptop-boot', device: 'laptop', title: 'Windows will not start',
    blurb: 'Error message, blue screen, or a loop that never reaches the desktop.', mins: 20,
    ifixit: { label: 'Windows boot problems', url: 'https://www.ifixit.com/Search?query=windows+won%27t+boot' },
    danger: true,
    steps: [
      { t: 'Photograph the error message',
        d: 'Before anything else. Photograph the whole screen including any code at the bottom. That code is the fastest route to the answer and it disappears when the machine restarts.' },
      { t: 'Unplug every USB device and restart',
        d: 'Flash drives, external drives, phones, printers. The machine may be trying to boot from a USB stick and finding nothing on it.' },
      { t: 'Let it fail three times on purpose',
        d: 'Power on, and as soon as you see the maker logo hold the power button until it switches off. Do that three times. On the fourth start Windows opens Automatic Repair by itself.' },
      { t: 'Run Startup Repair',
        d: 'From that menu: Advanced options, Troubleshoot, Advanced options, Startup Repair. Let it run — it can take twenty minutes and look stuck when it is not.' },
      { t: 'Stop before you reset anything',
        d: 'Do NOT choose "Reset this PC" or "Remove everything" unless your documents and photos are already backed up somewhere else. Those options erase the drive.',
        tip: 'Your files are almost certainly still fine. Wiping the drive to fix a boot problem is how people lose them. If in doubt, stop here and bring it in.' },
    ],
    giveUp: 'We can usually pull your files off the drive even when Windows will not start. Data recovery from a working drive is R400, and a reinstall with your files put back is R350. Bring it in before resetting anything.',
  },

  /* ----------------------------------------------------------- DESKTOP */
  {
    id: 'desktop-dead', device: 'desktop', title: 'Tower will not start',
    blurb: 'Nothing happens when you press the power button.', mins: 10,
    ifixit: { label: 'PC will not power on', url: 'https://www.ifixit.com/Search?query=pc+won%27t+power+on' },
    steps: [
      { t: 'Check the switch on the back of the tower',
        d: 'Most power supplies have their own I/O rocker switch next to where the cable plugs in. It gets knocked when the machine is moved or cleaned.' },
      { t: 'Prove the socket and the cable',
        d: 'Plug a lamp or a phone charger into the same socket. Then try the kettle lead from another appliance — those cables are all the same and they do fail.' },
      { t: 'Reseat the power cable at both ends',
        d: 'Push it firmly into the tower and into the wall. Half-out is invisible and behaves exactly like a dead machine.' },
      { t: 'Listen for a single beep and watch for a fan',
        d: 'Fans spinning with no picture is a display problem, not a power problem — check the monitor cable and that the monitor is on the right input.' },
    ],
    giveUp: 'A tower that stays silent on a proven socket usually needs a power supply. Bring the tower only — you can leave the monitor, keyboard and mouse at home.',
  },
  {
    id: 'desktop-nodisplay', device: 'desktop', title: 'No picture on the monitor',
    blurb: 'Tower runs but the screen says no signal.', mins: 10,
    ifixit: { label: 'Monitor no signal', url: 'https://www.ifixit.com/Search?query=monitor+no+signal' },
    steps: [
      { t: 'Check the monitor input',
        d: 'Press the monitor Source or Input button until it matches the cable you are using — HDMI, DisplayPort or VGA. A monitor sitting on the wrong input says "no signal" all day.' },
      { t: 'Reseat the video cable at both ends',
        d: 'Unplug and firmly replug at the monitor and at the tower. Screw in the thumbscrews if it is a VGA or DVI cable.' },
      { t: 'Use the right socket on the tower',
        d: 'If the tower has a graphics card, the display must plug into the card lower down, not the socket on the motherboard higher up. Swapping this over fixes it instantly.',
        tip: 'This one catches almost everybody after a machine has been moved.' },
      { t: 'Try another cable or another screen',
        d: 'A TV with HDMI works fine for this test.' },
    ],
    giveUp: 'Still nothing on a second screen means the graphics output or the RAM. Bring the tower in — diagnosis is R50.',
  },

  /* ----------------------------------------------------------- PRINTER */
  {
    id: 'printer-noprint', device: 'printer', title: 'Will not print',
    blurb: 'Job sent, nothing comes out.', mins: 12,
    ifixit: { label: 'Printer troubleshooting', url: 'https://www.ifixit.com/Search?query=printer+not+printing' },
    steps: [
      { t: 'Clear the queue',
        d: 'Settings, Bluetooth and devices, Printers. Open your printer, open the queue, cancel everything in it. One stuck job blocks every job behind it.' },
      { t: 'Check you are printing to the right printer',
        d: 'Windows likes to switch the default to "Microsoft Print to PDF" or a printer from a previous job. Look at the printer name in the print dialog before you click print.' },
      { t: 'Restart the printer and the computer, in that order',
        d: 'Switch the printer off at the wall for 30 seconds. Then restart the computer. This clears the spooler without touching any settings.' },
      { t: 'For a WiFi printer, check both are on the same network',
        d: 'A printer on the 2.4GHz network and a laptop on the 5GHz network cannot see each other, even though both say they are connected.' },
      { t: 'Reinstall the driver from the maker, not Windows',
        d: 'Search for your exact model number plus "driver" on the HP, Canon, Epson or Brother site. The generic driver Windows installs is a common cause of silent failures.' },
    ],
    giveUp: 'Printer setup at the shop is R200 and we send you home with it working. Bring the printer, the cable, and the laptop it needs to talk to.',
  },

  /* ----------------------------------------------------------- NETWORK */
  {
    id: 'net-nowifi', device: 'network', title: 'Cannot connect to WiFi',
    blurb: 'Network will not accept the password or does not appear.', mins: 12,
    ifixit: { label: 'WiFi troubleshooting', url: 'https://www.ifixit.com/Search?query=wifi+not+connecting' },
    steps: [
      { t: 'Test another device on the same WiFi',
        d: 'Does a second phone connect? That single question splits this in half — one device failing is a device problem, everything failing is the router or the line.',
        tip: 'Do this first. It saves you from an hour of resetting the wrong thing.' },
      { t: 'Forget the network and reconnect',
        d: 'Tap the network name, choose Forget, then connect again and type the password by hand. Passwords are case sensitive and an old saved one can be wrong.' },
      { t: 'Airplane mode on for ten seconds, then off',
        d: 'This rebuilds the whole wireless connection and is quicker than restarting.' },
      { t: 'Restart the router properly',
        d: 'Unplug it at the wall for a full 30 seconds, plug it back in, then wait three minutes without touching it. It has to re-sync with the line before the internet light settles.',
        tip: 'Three minutes. People give up at forty seconds and decide it did not work.' },
      { t: 'Check the account is actually paid and loaded',
        d: 'Prepaid data runs out, and debit orders bounce. The router keeps broadcasting WiFi perfectly either way, so it looks like a fault when it is a balance.' },
    ],
    giveUp: 'Bring the router in, or book a callout in Orange Farm for R150 plus the job. If you just need to get something sent today, our internet is R10 an hour.',
  },
  {
    id: 'net-noint', device: 'network', title: 'Connected but no internet',
    blurb: 'Full WiFi bars, nothing loads.', mins: 12,
    ifixit: { label: 'No internet connection', url: 'https://www.ifixit.com/Search?query=connected+but+no+internet' },
    steps: [
      { t: 'Check every device or only this one',
        d: 'If everything in the house is offline it is the router or the line. If it is only one device, it is that device.' },
      { t: 'Read the router lights',
        d: 'Photograph the front of the router. The power and WiFi lights being on means very little — the internet or DSL or LOS light is the one that matters. Red or off is your answer.',
        tip: 'Send us that photo on WhatsApp and we can usually tell you what it is straight away.' },
      { t: 'Restart the router and wait three full minutes',
        d: 'Off at the wall for 30 seconds. Then leave it completely alone for three minutes while it re-syncs.' },
      { t: 'Check the balance',
        d: 'Prepaid data finished, or a monthly debit that did not go through. This is the most common cause by a wide margin, and nothing on the router will tell you.' },
      { t: 'Try one site in a private window',
        d: 'If one page fails but others load, it is that site or a cached page, not your connection.' },
    ],
    giveUp: 'A red light on the router usually means the line, and that is a call to your provider rather than a repair. Send us the photo and we will tell you which it is before you spend the airtime.',
  },
];
